// Field type definitions for the Add Field feature
// Each type defines its icon, display name, format, default width, and validation

export const FIELD_TYPES = [
  {
    type: 'single_line_text',
    label: 'Single line text',
    icon: 'A',
    iconClass: 'font-bold text-sm',
    format: null,
    inputType: 'text',
    defaultWidth: 180,
    placeholder: 'Enter text',
    validate: () => true,
    parse: (v) => (v ?? '').toString().trim(),
  },
  {
    type: 'long_text',
    label: 'Long text',
    icon: '≡',
    iconClass: 'text-base',
    format: null,
    inputType: 'textarea',
    defaultWidth: 250,
    placeholder: 'Enter text',
    validate: () => true,
    parse: (v) => (v ?? '').toString().trim(),
  },
  {
    type: 'number',
    label: 'Number',
    icon: '#',
    iconClass: 'font-bold text-sm',
    format: 'number',
    inputType: 'number',
    defaultWidth: 120,
    placeholder: '0',
    validate: (v) => v === '' || !isNaN(Number(v)),
    parse: (v) => (v === '' || v == null ? null : Number(v)),
  },
  {
    type: 'currency',
    label: 'Currency',
    icon: '$',
    iconClass: 'font-bold text-sm',
    format: 'currency',
    inputType: 'number',
    defaultWidth: 130,
    placeholder: '0.00',
    validate: (v) => v === '' || !isNaN(Number(v)),
    parse: (v) => (v === '' || v == null ? null : Number(v)),
  },
  {
    type: 'checkbox',
    label: 'Checkbox',
    icon: '☑',
    iconClass: 'text-sm',
    format: 'checkbox',
    inputType: 'checkbox',
    defaultWidth: 100,
    placeholder: '',
    validate: () => true,
    parse: (v) => Boolean(v),
  },
  {
    type: 'single_select',
    label: 'Single select',
    icon: '◎',
    iconClass: 'text-sm',
    format: 'single_select',
    inputType: 'select',
    defaultWidth: 150,
    placeholder: 'Select an option',
    defaultOptions: ['Option 1', 'Option 2', 'Option 3'],
    validate: () => true,
    parse: (v) => (v ?? '').toString().trim(),
  },
  {
    type: 'date',
    label: 'Date',
    icon: '📅',
    iconClass: 'text-xs',
    format: 'date',
    inputType: 'date',
    defaultWidth: 130,
    placeholder: 'YYYY-MM-DD',
    validate: (v) => v === '' || !isNaN(Date.parse(v)),
    parse: (v) => (v === '' || v == null ? null : v),
  },
  {
    type: 'email',
    label: 'Email',
    icon: '✉',
    iconClass: 'text-xs',
    format: 'email',
    inputType: 'email',
    defaultWidth: 200,
    placeholder: 'email@example.com',
    validate: (v) => v === '' || /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v),
    parse: (v) => (v ?? '').toString().trim(),
  },
  {
    type: 'url',
    label: 'URL',
    icon: '🔗',
    iconClass: 'text-xs',
    format: 'url',
    inputType: 'url',
    defaultWidth: 200,
    placeholder: 'https://example.com',
    validate: (v) => {
      if (v === '') return true;
      try { new URL(v); return true; } catch { return false; }
    },
    parse: (v) => (v ?? '').toString().trim(),
  },
  {
    type: 'phone',
    label: 'Phone number',
    icon: '📞',
    iconClass: 'text-xs',
    format: 'phone',
    inputType: 'tel',
    defaultWidth: 140,
    placeholder: '(555) 123-4567',
    validate: () => true,
    parse: (v) => (v ?? '').toString().trim(),
  },
];

export const FIELD_TYPE_MAP = Object.fromEntries(FIELD_TYPES.map((ft) => [ft.type, ft]));
